title: My coding journey
author: Joseph Reilly
email: legendofreilly@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Day by day I learn something new about the world of programing,
  I want to share some of my experience.

# social links
twitter_username: flipnoggin
github_username:  JosephPR

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
